version: '2'
services:
  ecommerceep4-app:
    image: ecommerceep4
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://ecommerceep4-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=ecommerceEp4
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  ecommerceep4-mongodb:
    extends:
      file: mongodb.yml
      service: ecommerceep4-mongodb
